from __future__ import annotations

from dataclasses import dataclass

from .tree import Instance
from .datatypes import CFrame


enum: TypeAlias = int


""" To be autogenerated in the future """


@dataclass
class AnimationClip(Instance):
    Loop: bool = True
    Priority: enum = 2


@dataclass
class KeyframeSequence(AnimationClip):
    AuthoredHipHeight: float = 2


@dataclass
class Keyframe(Instance):
    Time: float = 0


@dataclass
class PoseBase(Instance):
    EasingDirection: enum = 0
    EasingStyle: enum = 0
    Weight: float = 1


@dataclass
class Pose(PoseBase):
    CFrame: CFrame = CFrame.Identity
